services:
  web:
    build: .
    restart: on-failure
    networks:
      - web
    ports:
      - "8080:8080"
  ollama:
    image: ollama/ollama:latest
    restart: on-failure
    networks:
      - web
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "5555:8080"
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - LLM=llama3
    restart: unless-stopped
    networks:
      - web

volumes:
  ollama:
  ollama-webui:

networks:
  web:
    driver: bridge
#    driver_opts:
#      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
